server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: DEBUG
  level.io.fdlessard.codebites.cloud.stream.listener: DEBUG

spring:
  application:
    name: client-kafka-listener-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_BROKER}
          configuration:
            security.protocol: SASL_SSL
            sasl.mechanism: PLAIN
            sasl.jaas.config: ${JAAS_CONFIG}
      bindings:
        receiveClient-in-0:
          destination: ${CLIENT_DESTINATION}
          group: ${CLIENT_GROUP}
          contentType: application/json

    function:
      definition: receiveClient