server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level.root: INFO
  level.io.fdlessard.codebites.cloud.stream.lambda: DEBUG

spring:
  application:
    name: client-lambda-functional-application
  output:
    ansi:
      enabled: always
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jackson:
    default-property-inclusion: non_null
    time-zone: UTC
    serialization:
      write_dates_as_timestamps: false
  cloud:
    function:
      definition: receiveKafkaEvent
